# Generated by Django 4.1.2 on 2022-12-23 06:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("electricity", "0002_battery_electricitypurchase_electricitysale_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConsumptionReading",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("kwh", models.DecimalField(decimal_places=3, max_digits=6)),
                ("occurred_at", models.DateTimeField(unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name="batterylevelreading",
            name="battery",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="level_readings", to="electricity.battery"
            ),
        ),
    ]
