"""
Django settings for sunbottle project.

Generated by 'django-admin startproject' using Django 4.1.2.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""
import datetime
import decimal
from pathlib import Path

from envparse import env

env.read_envfile()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env.str("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env.bool("DEBUG", default=False)

ALLOWED_HOSTS = env.list("ALLOWED_HOSTS", default=[])


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.humanize",
    "sunbottle.data.electricity",
    "sunbottle.interfaces",
    "sunbottle.interfaces.jobs",
    "sunbottle.interfaces.timers",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "sunbottle.interfaces.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [
            "sunbottle/interfaces/public/templates",
        ],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "sunbottle.interfaces.public.wsgi.application"


# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": env.str("DB_NAME", default="/opt/sunbottle/data/db.sqlite3"),
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = env.str("TIME_ZONE", default="Asia/Tokyo")

USE_I18N = True

# SQLite doesn't support storing datetimes with timezone information.
USE_TZ = False


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = "static"

STATICFILES_DIRS = [
    BASE_DIR / "sunbottle/interfaces/public/static/",
]

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


GENERATION_RETRIEVER_CLASS = "sunbottle.domain.sharp.generation.SharpGenerationRetriever"
STORAGE_RETRIEVER_CLASS = "sunbottle.domain.sharp.storage.SharpStorageRetriever"
BUYSELL_RETRIEVER_CLASS = "sunbottle.domain.sharp.buysell.SharpBuySellRetriever"
CONSUMPTION_RETRIEVER_CLASS = "sunbottle.domain.sharp.consumption.SharpConsumptionRetriever"

WEBDRIVER_INSTALL_PATH = env.str("WEBDRIVER_INSTALL_PATH", default="/opt/sunbottle/")
SHARP_LOGIN_MEMBERID = env.str("SHARP_LOGIN_MEMBERID", default="")
SHARP_LOGIN_PASSWORD = env.str("SHARP_LOGIN_PASSWORD", default="")

# Feed in Tariff
FIT = env.int("FIT", default=17)  # JPY per kWh

BILLING_PERIOD_START_YEAR = env.int("BILLING_PERIOD_START_YEAR", default=2022)
BILLING_PERIOD_START_MONTH = env.int("BILLING_PERIOD_START_MONTH", default=10)
BILLING_PERIOD_START_DAY = env.int("BILLING_PERIOD_START_DAY", default=15)

FIRST_BILLING_PERIOD_START = datetime.date(
    BILLING_PERIOD_START_YEAR, BILLING_PERIOD_START_MONTH, BILLING_PERIOD_START_DAY
)

# TODO: Move these to the database when someone tries to use Sunbottle with a non-Octopus provider.
FUEL_ADJUSTMENT_CHARGES: dict[datetime.date, decimal.Decimal] = {
    datetime.date(year=2022, month=10, day=15): decimal.Decimal("9.72"),
    datetime.date(year=2022, month=11, day=15): decimal.Decimal("11.92"),
    datetime.date(year=2022, month=12, day=15): decimal.Decimal("12.99"),
    datetime.date(year=2023, month=1, day=15): decimal.Decimal("13.04"),
    datetime.date(year=2023, month=2, day=15): decimal.Decimal("11.69"),
    datetime.date(year=2023, month=3, day=15): decimal.Decimal("10.25"),
    datetime.date(year=2023, month=4, day=15): decimal.Decimal("9.21"),
    datetime.date(year=2023, month=5, day=15): decimal.Decimal("7.21"),
    datetime.date(year=2023, month=6, day=15): decimal.Decimal("6.54"),
}

RENEWABLE_ENERGY_CHARGES: dict[datetime.date, decimal.Decimal] = {
    datetime.date(year=2022, month=10, day=15): decimal.Decimal("3.45"),
    datetime.date(year=2022, month=11, day=15): decimal.Decimal("3.45"),
    datetime.date(year=2022, month=12, day=15): decimal.Decimal("3.45"),
    datetime.date(year=2023, month=1, day=15): decimal.Decimal("3.45"),
    datetime.date(year=2023, month=2, day=15): decimal.Decimal("3.45"),
    datetime.date(year=2023, month=3, day=15): decimal.Decimal("3.45"),
    datetime.date(year=2023, month=4, day=15): decimal.Decimal("3.45"),
    datetime.date(year=2023, month=5, day=15): decimal.Decimal("1.40"),
    datetime.date(year=2023, month=6, day=15): decimal.Decimal("1.40"),
    datetime.date(year=2023, month=7, day=15): decimal.Decimal("1.40"),
}


GREEN_OCTOPUS: dict[tuple[int, int | None], decimal.Decimal] = {
    (0, 120): decimal.Decimal("19.68"),
    (121, 300): decimal.Decimal("24.05"),
    (301, None): decimal.Decimal("26.45"),
}

AGREEMENTS: dict[datetime.date, dict[tuple[int, int | None], decimal.Decimal]] = {
    datetime.date(year=2022, month=10, day=15): GREEN_OCTOPUS,
}
